CREATE TABLE IF NOT EXISTS t_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, -- 主键ID,
    username varchar(32) NOT NULL DEFAULT '', -- 用户名,
    avatar varchar(256) NOT NULL DEFAULT '', -- 头像,
    mobile varchar(128) NOT NULL DEFAULT '', -- 手机号,
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 创建时间,
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 最后修改时间,
    CONSTRAINT uk_t_user_mobile UNIQUE (mobile)
);

CREATE INDEX  IF NOT EXISTS idx_t_user_update_time ON t_user (update_time);